### ISSUE TITLE
major minor version error when trying to run the jar

### ISSUE THREAD

**Issue by vandanachadha** [dacduong/escpos-printer-simulator#4]
Hello, am getting the error below when I run the jar on java1.7 on an aws instance: Is there a specific java version the jar will run, or do I need to build it within that environment?

$ java -jar python_files/ESCPosPrinterSimulator.jar 9100 dist/public/kitcen_prints.out 200 &
$ Exception in thread "main" java.lang.UnsupportedClassVersionError: biz/iteksolutions/Program : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:326)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

$ java -version
java version "1.7.0_261"
OpenJDK Runtime Environment (amzn-2.6.22.1.83.amzn1-x86_64 u261-b02)
OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)

**Comment by vandanachadha** [comment]
Ok, it worked when I upgraded to java version 1.8
